package com.ruthvikbr.starbucksindiacompose.ui.utils

const val CHECK_MARK_ANIMATION_DURATION = 250
const val OUTER_CIRCLE_ANIMATION_DURATION = 1000
const val OUTER_CIRCLE_SCALE_ANIMATION_DURATION = 250
const val INNER_CIRCLE_ANIMATION_DURATION = 250
const val REGISTRATION_SCREEN_SLIDE_OUT_ANIMATION = 300
const val REGISTRATION_SCREEN_SLIDE_IN_ANIMATION = 300
